### ISSUE TITLE
qunit-harness doesn't obtain test results in Firefox 47

### ISSUE THREAD

**Issue by georgiy-abbasov** [AlexanderMoskovkin/qunit-harness#35]
We can't get access to `window.global_test_results` in Firefox 47 while getting test results. Problem remains, if we try to replace `window` with `document`.

**Comment by georgiy-abbasov** [comment]
In private discussion with Sauce Labs support it became clear, that the problem is with version  47.0. Support engineer recommends to wait, until the browser will be updated to version 47.0.1 on Sauce Labs side.

**Comment by georgiy-abbasov** [comment]
Support engineer reported, that issue has been resolved.
https://support.saucelabs.com/customer/portal/questions/16341558-problem-with-executing-script-via-webdriver-in-firefox-47

**Comment by AlexanderMoskovkin** [comment]
@georgiy-abbasov Please, update the `firefox` version in `testcafe` and `testcafe-hammerhead` repos
