### ISSUE TITLE
Add possibility to rerun fixture

### ISSUE THREAD

**Issue by miherlosev** [AlexanderMoskovkin/qunit-harness#41]
We have a tests what load content from remote sources.
Because of this any tests sometimes are failed.
To fix it we need to rerun fixture that contains failed tests.

Also we need a way to mark fixture which we will rerun.

**Comment by inikulin** [comment]
@miherlosev Why we load something from external resources for testing?

**Comment by miherlosev** [comment]
Server that respond qunit tests pages and test data is running on travis virtual machine.
QUnit tests are running on the saucelabs virtual machine.
QUnit tests on saucelabs load data from travis.

I don't know why why it is so done.  Maybe we cann't run http server on saucelabs virtual machine.

**Comment by AlexanderMoskovkin** [comment]
We took a decision to don't implement this. We will handle the problem with connection with [this](https://github.com/AlexanderMoskovkin/qunit-harness/issues/8) solution
